#!/usr/bin/env bash
set -aeuo pipefail

# create the dotenv file if it doesn't exist
if [ ! -f .env ]; then
  cp .env.default .env
fi

if [ ! -f src/.env ]; then
  cp .env src/.env
fi

source .env

npm  i --prefix src --verbose && npm run $@ --prefix src
